name: Words by CrisisModel
description: Words written by Autumn
meta_description: "This is Autumn's word dump"

markdown: kramdown
highlighter: rouge
logo: 'https://words.crisismodel.com/assets/images/logo.png'
paginate: 15
baseurl: 'https://words.crisismodel.com/'
domain_name: 'https://words.crisismodel.com/'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://words.crisismodel.com'
author:         'Autumn'
