name: Words by CrisisModel
description: Words written by Autumn Tera
meta_description: "This is Autumn's word dump"

markdown: kramdown
highlighter: rogue
logo: false
paginate: 15
baseurl: /
domain_name: 'https://words.crisismodel.com'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://words.crisismodel.com'
author:         'Autumn Tera'
baseurl:        'https://words.crisismodel.com/'
logo:           'assets/images/logo.png'
cover:          'https://i.picsum.photos/id/1063/4867/3215.jpg'
