name: CrisisModel: Words
description: Words written by Autumn.
meta_description: "This is Autumn's word dump."

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://words.crisismodel.com'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://words.crisismodel.com'
author:         'Autumn Boyhan'
