name: Words by CrisisModel
description: Words written by Autumn Tera
meta_description: "This is Autumn's word dump"

markdown: kramdown
highlighter: rogue
logo: 'https://words.crisismodel.com/assets/images/logo.png'
paginate: 15
baseurl: /
domain_name: 'https://words.crisismodel.com'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://words.crisismodel.com'
author:         'Autumn Tera'
